# Generated by Django 3.1.4 on 2020-12-04 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BloodManagement', '0002_remove_bloodpacket_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='blood_required',
        ),
    ]
