# Generated by Django 3.1.4 on 2020-12-05 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BloodManagement', '0006_auto_20201205_0506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
