# Generated by Django 3.1.4 on 2020-12-05 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BloodManagement', '0007_auto_20201205_0602'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloodpacket',
            name='used',
        ),
    ]
